apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
    role: api
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 9999
    targetPort: 9999
  selector:
    app: config-service
    role: api
    tier: backend
